import React, { useEffect, useState } from 'react';
import { LuCpu, LuChevronDown, LuActivity } from 'react-icons/lu';
import './agents.scss';

// ─── Agents data contract ────────────────────────────────────────────
// Filled from public/agents-data.json — hand-edited today, designed to be
// regenerated by a local agent-runner later (same pattern as now-data.json).
// `status`: running (live, green pulse) · idle (sleeping, amber) · done
// (finished a run, indigo) · error (red). `startedAt` is ISO — running agents
// tick a live uptime from it.
type AgentStatus = 'running' | 'idle' | 'done' | 'error';

interface Agent {
  id: string;
  name: string;
  status: AgentStatus;
  model: string;
  task: string;
  startedAt?: string | null;
  tokensToday?: number | null;
  tasksDone?: number | null;
  log?: string[];
  shipped?: string[];
}

interface AgentsData {
  updatedAt: string | null;
  agents: Agent[];
}

// ─── Feature flag ────────────────────────────────────────────────────
// The "Agents running" panel is hidden until real agents are actually
// running around the clock and writing agents-data.json. Flip this to
// `true` (or set REACT_APP_SHOW_AGENTS=true at build time) to switch it on.
const AGENTS_ENABLED =
  process.env.REACT_APP_SHOW_AGENTS === 'true' || false;

const STATUS_LABEL: Record<AgentStatus, string> = {
  running: 'Running',
  idle: 'Idle',
  done: 'Done',
  error: 'Error',
};

// Pick a provider tint from the model id so each model gets its own badge
// colour without a hand-maintained lookup table.
function providerOf(model: string): { label: string; key: string } {
  const m = model.toLowerCase();
  if (m.includes('claude') || m.includes('opus') || m.includes('sonnet') || m.includes('haiku') || m.includes('fable'))
    return { label: 'Anthropic', key: 'anthropic' };
  if (m.includes('gpt') || m.includes('o1') || m.includes('o3')) return { label: 'OpenAI', key: 'openai' };
  if (m.includes('gemini')) return { label: 'Google', key: 'google' };
  if (m.includes('llama')) return { label: 'Meta', key: 'meta' };
  if (m.includes('mistral')) return { label: 'Mistral', key: 'mistral' };
  return { label: 'Model', key: 'other' };
}

const fmtNum = (n: number | null | undefined): string =>
  n === null || n === undefined ? '—' : n.toLocaleString();

// Live "running for 4m 12s" elapsed string from an ISO start time.
function elapsed(from: string, now: number): string {
  const start = new Date(from).getTime();
  if (Number.isNaN(start)) return '—';
  let s = Math.max(0, Math.floor((now - start) / 1000));
  const h = Math.floor(s / 3600); s -= h * 3600;
  const m = Math.floor(s / 60); s -= m * 60;
  if (h) return `${h}h ${m}m`;
  if (m) return `${m}m ${s}s`;
  return `${s}s`;
}

const AgentCard: React.FC<{ agent: Agent; now: number }> = ({ agent, now }) => {
  const [open, setOpen] = useState(false);
  const prov = providerOf(agent.model);
  const live = agent.status === 'running';
  const hasDetail = (agent.log?.length || 0) > 1 || (agent.shipped?.length || 0) > 0;
  const headLine = agent.log?.[0];

  return (
    <div className={`agent-card agent-card--${agent.status}`}>
      <div className="agent-card__top">
        <span className="agent-card__status" aria-hidden="true" />
        <span className="agent-card__name">{agent.name}</span>
        <span className={`agent-card__model agent-card__model--${prov.key}`} title={`${prov.label} · ${agent.model}`}>
          <LuCpu /> {agent.model}
        </span>
        <span className="agent-card__state">{STATUS_LABEL[agent.status]}</span>
      </div>

      <p className="agent-card__task">{agent.task}</p>

      {headLine && (
        <div className="agent-card__live" aria-label="latest activity">
          <span className="agent-card__prompt">›</span>
          <span className={`agent-card__logline${live ? ' agent-card__logline--blink' : ''}`}>{headLine}</span>
        </div>
      )}

      <div className="agent-card__meta">
        {agent.startedAt && (
          <span className="agent-card__metric">
            <LuActivity />
            {live ? `up ${elapsed(agent.startedAt, now)}` : agent.status === 'idle' ? 'sleeping' : 'last run'}
          </span>
        )}
        {agent.tasksDone !== null && agent.tasksDone !== undefined && (
          <span className="agent-card__metric">{fmtNum(agent.tasksDone)} tasks done</span>
        )}
        {agent.tokensToday !== null && agent.tokensToday !== undefined && (
          <span className="agent-card__metric">{fmtNum(agent.tokensToday)} tok today</span>
        )}
        {hasDetail && (
          <button
            type="button"
            className={`agent-card__toggle${open ? ' agent-card__toggle--open' : ''}`}
            onClick={() => setOpen((v) => !v)}
            aria-expanded={open}
          >
            log <LuChevronDown />
          </button>
        )}
      </div>

      {open && hasDetail && (
        <div className="agent-card__detail">
          {(agent.log?.length || 0) > 0 && (
            <ol className="agent-card__feed">
              {agent.log!.map((l, i) => (
                <li key={i} className="agent-card__feeditem"><span className="agent-card__prompt">›</span>{l}</li>
              ))}
            </ol>
          )}
          {(agent.shipped?.length || 0) > 0 && (
            <div className="agent-card__shipped">
              <span className="agent-card__shipped-label">Shipped</span>
              <div className="agent-card__chips">
                {agent.shipped!.map((s, i) => (
                  <span className="agent-card__chip" key={i}>{s}</span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

const AgentSkeleton: React.FC = () => (
  <div className="agent-card agent-card--skeleton" aria-hidden="true">
    <div className="agent-card__top">
      <span className="agent-card__status" />
      <span className="now-skel now-skel--line" style={{ width: '110px' }} />
    </div>
    <span className="now-skel now-skel--line" style={{ width: '90%', marginTop: 10 }} />
    <span className="now-skel now-skel--line now-skel--short" style={{ marginTop: 8 }} />
  </div>
);

const AgentsRunning: React.FC = () => {
  const [data, setData] = useState<AgentsData | null>(null);
  const [now, setNow] = useState<number>(() => Date.now());

  useEffect(() => {
    if (!AGENTS_ENABLED) return;
    fetch(`${process.env.PUBLIC_URL}/agents-data.json`, { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : null))
      .then(setData)
      .catch(() => {});
  }, []);

  // Tick once a second so running agents show a live, climbing uptime.
  useEffect(() => {
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduce) return;
    const id = window.setInterval(() => setNow(Date.now()), 1000);
    return () => window.clearInterval(id);
  }, []);

  // Flagged off → render nothing at all.
  if (!AGENTS_ENABLED) return null;
  // Loaded but empty → hide the whole section.
  if (data && (!data.agents || data.agents.length === 0)) return null;

  const agents = data?.agents ?? [];
  const liveCount = agents.filter((a) => a.status === 'running').length;

  return (
    <section className="now-agents" aria-label="My AI agents running">
      <div className="now-media__head">
        <h2 className="now-media__title">
          <LuCpu className="now-icon" /> Agents running
          {data && (
            <span className={`now-agents__live${liveCount > 0 ? ' now-agents__live--on' : ''}`}>
              <span className="now-agents__livedot" aria-hidden="true" />
              {liveCount > 0 ? `${liveCount} live` : 'idle'}
            </span>
          )}
        </h2>
        <span className="now-media__auto">Autonomous · self-running</span>
      </div>

      <p className="now-agents__lead">
        A live look at the AI agents I have running in the background — what each one is working on
        right now, the model behind it, and what it's already shipped.
      </p>

      <div className="now-agents__grid">
        {data === null
          ? Array.from({ length: 3 }).map((_, i) => <AgentSkeleton key={i} />)
          : agents.map((a) => <AgentCard key={a.id} agent={a} now={now} />)}
      </div>
    </section>
  );
};

export default AgentsRunning;
