// Generates public/sitemap.xml with one <url> per (page x locale) and reciprocal
// hreflang alternates on each. Run: node scripts/gen-sitemap.mjs
// Keep the PAGES list in sync when adding an indexable page or blog post.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE = 'https://eduardhvizdak.com';
const LOCALES = ['en', 'sk', 'cs'];

// Indexable pages only. noindex pages (styleguide, share-preview, ai-employee,
// 404) are intentionally excluded. lastmod is optional.
const PAGES = [
  { path: '/', lastmod: '2026-07-11', priority: '1.0', changefreq: 'weekly' },
  { path: '/services', lastmod: '2026-07-11', priority: '0.9', changefreq: 'monthly' },
  { path: '/blog', lastmod: '2026-07-11', priority: '0.8', changefreq: 'weekly' },
  { path: '/now', lastmod: '2026-07-11', priority: '0.6', changefreq: 'weekly' },
  { path: '/things', lastmod: '2026-07-11', priority: '0.5', changefreq: 'monthly' },
  { path: '/blog/newsmatics-hackathon', lastmod: '2026-06-27', priority: '0.7' },
  { path: '/blog/digital-fairness-act-youth-dialogue', lastmod: '2026-06-25', priority: '0.7' },
  { path: '/blog/zero-to-done', lastmod: '2026-06-08', priority: '0.7' },
  { path: '/blog/erasmus-bridges-not-walls', lastmod: '2026-05-06', priority: '0.7' },
];

// Mirror src/config/locale.ts localizedPath(): en unprefixed, sk/cs prefixed.
const loc = (p, l) => (l === 'en' ? p : p === '/' ? `/${l}` : `/${l}${p}`);

const alternates = (p) =>
  [
    ...LOCALES.map((l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${SITE}${loc(p, l)}"/>`),
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${loc(p, 'en')}"/>`,
  ].join('\n');

const urls = PAGES.flatMap((page) =>
  LOCALES.map((l) => {
    const lines = [
      '  <url>',
      `    <loc>${SITE}${loc(page.path, l)}</loc>`,
      page.lastmod ? `    <lastmod>${page.lastmod}</lastmod>` : null,
      page.changefreq ? `    <changefreq>${page.changefreq}</changefreq>` : null,
      page.priority ? `    <priority>${page.priority}</priority>` : null,
      alternates(page.path),
      '  </url>',
    ].filter(Boolean);
    return lines.join('\n');
  })
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs. Do not hand-edit; edit PAGES and rerun. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`;

const out = path.resolve(__dirname, '..', 'public', 'sitemap.xml');
fs.writeFileSync(out, xml);
console.log(`[gen-sitemap] wrote ${PAGES.length * LOCALES.length} urls to ${out}`);
